name: Python CI with Render Deploy

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Trigger Render deploy
        if: success()  # Only run if tests pass
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

