name: Python CI with Render Deploy

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Deploy to Render if tests pass
        if: success()
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

